name: Pyinstaller package

on:
  push:
    branches: [ master, feature ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pylint
    - name: Install
      run: |
        python -m pip install .
    - name: Make executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python-version: 3.12
        spec: 'packaging/gui-tklinux.spec'
        upload_exe_with_name: 'isp-programmer-${{ matrix.os }}'
